project:
  type: website
  output-dir: docs
  
execute:
  freeze: true

website:
  title: "Data by Andre"
  navbar:
    background: "#003049"
    left:
      - icon: github
        href: https://github.com/SoyAndrea/
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/andreasociologa/
    right:
      - href: index.qmd
        text: Sobre Mi
      - text: "Curriculum"
        menu:
          - href: cv_ES.qmd
      - href: conoce-arcenso.qmd
      - href: blog.qmd
      - href: talleres.qmd
      - href: comunidad.qmd 
      




format:
  html:
    theme: minty
    css: styles.css
    toc: true
    lang: es
    linkcolor: "#003049"
    fontsize: 13pt
    citations-hover: true
    footnotes-hover: true
    code-link: true


editor: visual

